### ISSUE TITLE
clickhouse-rs does not compile with the latest version of tokio 0.3.5

### ISSUE THREAD

**Issue by godfryd** [suharev7/clickhouse-rs#118]
I'm getting such error:
```
error[E0277]: `GetHandle` is not a future
  --> src/main.rs:72:22
   |
72 |     let mut client = pool.get_handle().await?;
   |                      ^^^^^^^^^^^^^^^^^^^^^^^ `GetHandle` is not a future
   |
   = help: the trait `Future` is not implemented for `GetHandle`
   = note: required by `poll`
```

If I get back to tokio 0.1.22 it compiles.

Is it possible to fix this?

**Comment by let4be** [comment]
Same thing... sigh
For some reason all libraries in rust that touch tokio are broken in one or another way, impossible to get something to work

**Comment by ArunGust** [comment]
if you have tokio vesion conflict with other libraries, you could try this

   ```
 let rt = Runtime::new().unwrap();
    rt.block_on(async {
        // call your dependency
        let pool = Pool::new(database_url);
        let mut client = pool.get_handle().await?;
        println!("get_handle OK");
    
        let dropddl = format!( r"DROP TABLE IF EXISTS {}", table_name.clone());
        let drop_result = client.execute(dropddl).await?;
        println!("DROP TABLE IF EXISTS done {:?}", drop_result);
    })
```
